<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-23 15:34
=======
# Generated by Django 5.0.4 on 2024-05-30 15:50
>>>>>>> 01bbfdde4822d20c23b39ba778a11f03818c48f0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('cite_url', models.URLField()),
                ('star', models.DecimalField(decimal_places=1, max_digits=2)),
                ('like_cnt', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=50)),
                ('latitude', models.FloatField(default=37.579472)),
                ('longitude', models.FloatField(default=126.976872)),
            ],
            options={
                'db_table': 'Cinema',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('poster_url', models.URLField(blank=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main.cinema')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
