# Generated by Django 5.0.4 on 2024-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
