# Generated by Django 5.0.4 on 2024-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='view_url',
            field=models.URLField(blank=True),
        ),
    ]
