<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-23 15:34
=======
# Generated by Django 5.0.4 on 2024-05-30 15:50
>>>>>>> 01bbfdde4822d20c23b39ba778a11f03818c48f0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('email', models.EmailField(max_length=50, unique=True)),
=======
                ('email', models.EmailField(max_length=50)),
>>>>>>> 01bbfdde4822d20c23b39ba778a11f03818c48f0
                ('nickName', models.CharField(default=' ', max_length=20)),
                ('posts', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('likePosts', models.TextField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
