# Generated by Django 5.0.4 on 2024-06-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitylike',
            old_name='writer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='community',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='rating_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
