# Generated by Django 5.0.4 on 2024-06-08 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_writer_communitylike_user_community_rating_and_more'),
        ('main', '0002_cinema_view_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='community',
            name='rating_cnt',
        ),
        migrations.AddField(
            model_name='community',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CinemaRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_cinema', to='main.cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
