# Generated by Django 5.0.4 on 2024-06-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_community_rating_remove_community_rating_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='rating_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='writer',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='CinemaRating',
        ),
    ]
