# Generated by Django 5.0.4 on 2024-06-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_rating_community_rating_cnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='rating_cnt',
        ),
    ]
