# Generated by Django 5.0.4 on 2024-05-27 20:34

import mypage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviehistory',
            name='poster',
            field=models.ImageField(null=True, upload_to=mypage.models.mypage_image_upload_path),
        ),
    ]
